"""
Django settings for labelingsystem project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

# Uncomment following if you want to run direct server.
# STATIC_DIR = os.path.join(BASE_DIR, 'static')
# MEDIA_DIR = os.path.join(BASE_DIR, 'media')

# Path to store all the media files.
MEDIA_DIR = 'your path'

# Path to store all the static files.
STATIC_DIR = 'your path'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'your key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed from all host
ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'cuser.CUser'

# Crispy Form using Bootstrap3
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Application definition

INSTALLED_APPS = [
    'admin_view_permission',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #apps
    'account',
    'bootstrap3',
    'crispy_forms',
    'cuser',
    'label',
    'labelingsystem',
    'post',
    'quiz',
    'response',
    'task',
    'classify',
    'smart_selects',
    'django_select2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'labelingsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'labelingsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'your database name',
        'USER': 'your user name',
        'PASSWORD': 'your password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = STATIC_DIR
FORCE_SCRIPT_NAME = ''
# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR
# Login
LOGIN_URL = 'account:login'
LOGIN_REDIRECT_URL = 'home'
# Logout
LOGOUT_REDIRECT_URL = 'account:login'
# Emails
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'your user name'
EMAIL_HOST_PASSWORD = 'your password'
EMAIL_FROM = 'your from email address'
EMAIL_TO = 'your to email address'
# This will print emails to STDOUT (use for testing)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# This will actually send emails (uncomment when we want to actually send emails)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
