# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180831_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='table_name',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Tablename', verbose_name='table_name'),
        ),
    ]
