# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-30 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import label.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_task_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('vectorizer', models.CharField(choices=[('count', 'count'), ('tfidf', 'tfidf')], default='tfidf', max_length=50)),
                ('classifier', models.CharField(choices=[('cnn', 'cnn'), ('rf', 'rf'), ('svm', 'svm')], default='cnn', max_length=50)),
                ('conf', models.CharField(max_length=1000, verbose_name='configuration')),
                ('upload_task', models.FileField(default=None, editable=False, upload_to='post list', verbose_name=label.models.Label)),
                ('creator', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='task')),
            ],
            options={
                'verbose_name_plural': 'classifications',
                'verbose_name': 'classification model',
            },
        ),
    ]
