# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_auto_20180830_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='conf',
            field=models.CharField(max_length=5000, verbose_name='configuration'),
        ),
    ]
